import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { userConfig, socials, links, profilePicture } from '../src/config'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                {/* Photo */}
                {/* Altere aqui o seu avatar. Utilizar proporção de 1:1 (Quadrado) */}
                <div className="container-fluid photo" id="top">
                    <div className="row">
                        <div className="col">
                            <p>
                                <Image src={profilePicture} />
                            </p>
                        </div>
                    </div>
                </div>

                {/* Title */}
                <div className="container-fluid title">
                    <div className="row">
                        <div className="col">
                            <h1>{ userConfig.name }</h1>
                            <h2>{ userConfig.github }</h2>
                        </div>
                    </div>
                </div>

                {/* Bio */}
                <div className="container-fluid bio">
                    <div className="row">
                        <div className="col">
                            <p>{ userConfig.description }</p>
                        </div>
                    </div>
                </div>

                {/* Links */}
                <div className="container-fluid links">
                    <div className="row">
                        <div className="col">
                            { 
                                links.map((currentLink, index) => {
                                    return (
                                        <a key={index} href={currentLink.url} target="_blank" className="botao">
                                            <p>{currentLink.label}</p>
                                        </a>
                                    )
                                }) 
                            }
                        </div>
                    </div>
                </div>

                {/* Social */}
                <div className="container-fluid social">
                    <div className="row">
                        <div className="col">
                            <ul>
                                {/* Copiar e colocar o modelo dos icons // Para outros icons, veja a biblioteca do Boostrap 5 */}
                                { 
                                    socials.map((socialMedia, index) => {
                                        return (
                                            <li key={index}><a href={socialMedia.url} target="_blank"><i className={socialMedia.icon} style={{ fontSize: '2rem' }} title={socialMedia.label}></i></a></li>
                                        )
                                    }) 
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </main>


            <footer>
                <div className="container-fluid">
                    <div className="row">
                        <div className="col">
                            {/* Pode alterar se quiser, mas ficarei muito grato caso possa deixar um link para o meu site :) */}
                            <p>
                                I would like to thank <a href="https://ehayashi.com" target="_blank" title="EHayashi">EHayashi</a> for the nice template!
                                <br />
                                Made with <a href="https://getbootstrap.com/" target="_blank" title="Bootstrap">Bootstrap 5</a>
                            </p>
                            <p>&nbsp;</p>
                            <p>
                                <a href="#top"><i className="bi bi-arrow-up-circle-fill"></i> Back to top</a>
                            </p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    )
}

export default Home
